language: python
python:
- '2.7'
before_install:
- git log --no-merges -n 1 > changes.md
install:
- pip install -r requirements.txt
script:
- make clean
- make release
before_deploy:
- rvm 1.9.3 do gem install mime-types -v 2.6.2
deploy:
  provider: releases
  api_key:
    secure: Wm7wncirAYROoMUb5wQ+F+FJcqJ94ROgNTCZkTAO8EniR/WmN66fOBYOoAQkxjPaVlH0yZGmVKrBkuI58B6o8X2hCVaCfUz7611JxwQvcpX5YZaMO1yH1ukr5kGXnE+iVE/ebA06WSincnnNKC+Sx/AWZaCoFjEHnHSeSGADMsw=
  file_glob: true
  file:
  - TestFlightCore*.zip
  - TestFlightConfigStock*.zip
  skip_cleanup: true
  on:
    repo: KSP-RO/TestFlight
    tags: true
    all_branches: true
notifications:
  irc:
    channels:
    - irc.esper.net#RO
    skip_join: true
    use_notice: true
    on_success: change
    on_failure: change
    template:
    - 'Build #%{build_number} - %{branch} - %{result}'
    - "%{commit_message}"
after_success:
- make deploy
env:
  global:
  - secure: KK4zCiujTh58oH6dX5Hphi357mwnDrjFS9oVbCOaDUk+Uwz6qhEUgwvWZu5a2/wEFFRV4JyRm27QsAdDAJ0qy0f+SW6yoTIrdYx3PTDuWl+CL4L5yGV6K/LYrGrtDz1AXLFupfhgPcoB62dYDmZmzCHNioB8BY5zuuA9o3fzxcU=
  - secure: fLfigVPg9ubGokcauE+797nTcw63TPjsJXmKrzG1JqsvzCXzd4qVrbw6zuwO7rRzAaimqwbxjIVxZFqzJHb9jCut3FcM+iMranewM75qRErqSZh14sImWi9YMRIl5wkb0xElGIbPYAY1aqR89V8m20CthTX21/dfmJhTa8EyAPM=
  - secure: TTeep3257heuzclYnRD5r+fKCuilW+heZynKplW30SGckkrdtcZe6lbYs0tQ+5o3a8X1y41TQHKgXIJQM0P2DIfKODT9iofpu4gCIZoL+cF7Mj3BKoBHz7zKtYoCMdP/fkTh8cJMpV5nERhiADmC4hSdghwUmydLFI2VS7IUIO0=
  - secure: U9SivVZAeUWqr+WlAjeZC6cWHGJ07IN81koIVSQxXPcpgTBoGTkrSBPFcUTer0u12BCFY9W6W4ffTvXhVm9QSKn1Cjzh6TucB5zKRDnnx8YcheoM6tgR/0muctrqbH45FAVGZ1XnqbD1H4ZQqCcPMmbECoewwzFnZP5+OvZMY2c=
  - secure: bIWddpMEbIIUoNAnIeITErojIQ2PQJmOfEpdDf/IgrWnkTWBu4ibtRqfvPi9J5qrfphbkn3pHfoMBSsbUrhCej86AicTd+ZlpSq91vJC+TOxdTbchBgcNiq+g27BOpgHVYc/YkurafP7ktUPO/drWL3Fb6BXfPfUHPwlXgxdq10=
  - secure: SGGsoiKWIWU6UIyPhmpn1U+eSP+alJsESsqoWO6RAzzbyXHZACJk5Wu0iECj69BlDtfOWpHCLsrbytWGVeIG00RrDmdWOKdJtm+YbKqsurxLiy6eKAn+eckj9aCiVP4bnfxQZ8nyf+oZkCfClLu0wSnJ1bbvZSpH+AWO7IiF0uo=
  - secure: g8CdANgd1tOLqQclHZJpCkPP87FP72dORzXlJevXaCC3r7zm18oLphbCJLWtFueJHjPL0KcEpFrA3yOhd14V6p703GiqirLJEGfAlPH0Jf/1/OcnKKodqR7+dPRKoeHB9abNkJvCH4Ky3OL4PG41kXUlvw6vLU1FlXlohGcOCAE=
  - secure: euWk+O9HXVSLmzTg9Fs9LPh+MM1R4wBJKMhnTT9INMwr7eIqyz2jvLhBtSM0GyHr1lCS7hc5kY5tbdYfg0En5cn6FbdFj6L64AMns65Af6maMcRLudZFTVqS1/1PJ5Xxmb5gLl9Jgvr29waNVLyqbh/vHlWFuuMaUCnSEDg4osA=
